from . import config_payroll_day
from . import hr_public_holiday_line
from . import hr_public_holiday
from . import hr_payslip_extend
from . import hr_holidays_status_extend
from . import date_to_payroll
from . import hr_bsc_department
from . import hr_kpi_employee_line
from . import hr_kpi_employee
from . import hr_payment_insurance
from . import hr_holidays
